In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
iris_data = iris.data

In [4]:
iris_target = iris.target

In [5]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(2)

In [6]:
iris_transformed = svd.fit_transform(iris_data)

In [7]:
print(iris_data[:5])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]


In [8]:
print(iris_transformed[:5])

[[ 5.91220352  2.30344211]
 [ 5.57207573  1.97383104]
 [ 5.4464847   2.09653267]
 [ 5.43601924  1.87168085]
 [ 5.87506555  2.32934799]]


In [10]:
#或者
# scipy对矩阵做分解
from scipy.linalg import svd
import numpy as np
D = np.array([[1,2],[1,3],[1,4]])

In [11]:
print(D)

[[1 2]
 [1 3]
 [1 4]]


In [12]:
U,S,V = svd(D, full_matrices=False)

In [13]:
print(U)

[[-0.39133557  0.8247362 ]
 [-0.5605708   0.13817999]
 [-0.72980603 -0.54837623]]


In [14]:
print(S)

[ 5.64015854  0.43429448]


In [15]:
print(V)

[[-0.29816758 -0.95451354]
 [ 0.95451354 -0.29816758]]


In [16]:
print(np.diag(S))

[[ 5.64015854  0.        ]
 [ 0.          0.43429448]]


In [17]:
print(U.dot(np.diag(S)))

[[-2.20719466  0.35817838]
 [-3.16170819  0.06001081]
 [-4.11622173 -0.23815677]]


In [18]:
print(np.dot(U.dot(np.diag(S)), V))

[[ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]]
